# The Docker image that will be used to build your app
image: alpine:latest
# Functions that should be executed before the build script is run
before_script: []
pages:
  stage: deploy
  script:
    - "echo 'deploying $CI_COMMIT_SHA'"
  artifacts:
    paths:
      - src/
  publish: src/
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment: production

